# Generated by Django 3.2.5 on 2021-07-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_worker',
            field=models.BooleanField(db_index=True, default=False, verbose_name='сотрудник'),
        ),
    ]
