# Generated by Django 3.2.5 on 2021-07-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='актив'),
        ),
    ]
