# Generated by Django 3.2.5 on 2021-07-22 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('ремонт', 'ремонт'), ('обслуживание', 'обслуживание'), ('консультация', 'консультация')], max_length=16, verbose_name='тип заявки')),
                ('content', models.CharField(max_length=256, verbose_name='описание заявки')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='активна')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='изменена')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='клиент')),
            ],
        ),
    ]
