# Generated by Django 3.2.5 on 2021-07-23 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_client_is_worker'),
        ('main_app', '0002_auto_20210723_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_w', to='auth_app.client', verbose_name='сотрудник'),
        ),
    ]
