# Generated by Django 3.2.5 on 2021-07-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_application_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('открыта', 'открыта'), ('в работе', 'в работе'), ('закрыта', 'закрыта')], default=1, max_length=16, verbose_name='статус заявки'),
            preserve_default=False,
        ),
    ]
